[package]
name = "serde-dummy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"

[dev-dependencies]
serde_json = "1.0.64"
